version: 0.2
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "aws-codebuild-python-lambda"
        Alias: "testalias"
        CurrentVersion: "$LATEST"
        TargetVersion: "$LATEST"
Hooks:
  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"pandas
